// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGmBXV8Q6cSZYVPTW9XbeKpfg1GoW_4Os',
    appId: '1:1084688936474:web:632524ba88d8164805aba3',
    messagingSenderId: '1084688936474',
    projectId: 'singup-login-realtime-b4ef7',
    authDomain: 'singup-login-realtime-b4ef7.firebaseapp.com',
    databaseURL: 'https://singup-login-realtime-b4ef7-default-rtdb.firebaseio.com',
    storageBucket: 'singup-login-realtime-b4ef7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-wBmod4xvGrC5pX4AwEA9_rFoCnp0JY',
    appId: '1:1084688936474:android:4120b97c65ff87a305aba3',
    messagingSenderId: '1084688936474',
    projectId: 'singup-login-realtime-b4ef7',
    databaseURL: 'https://singup-login-realtime-b4ef7-default-rtdb.firebaseio.com',
    storageBucket: 'singup-login-realtime-b4ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGjcSqBZbi_sx_OBV0oeDjPx-XjxjoN8',
    appId: '1:1084688936474:ios:df1e54634a2eb1b705aba3',
    messagingSenderId: '1084688936474',
    projectId: 'singup-login-realtime-b4ef7',
    databaseURL: 'https://singup-login-realtime-b4ef7-default-rtdb.firebaseio.com',
    storageBucket: 'singup-login-realtime-b4ef7.firebasestorage.app',
    iosBundleId: 'com.example.chatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvGjcSqBZbi_sx_OBV0oeDjPx-XjxjoN8',
    appId: '1:1084688936474:ios:df1e54634a2eb1b705aba3',
    messagingSenderId: '1084688936474',
    projectId: 'singup-login-realtime-b4ef7',
    databaseURL: 'https://singup-login-realtime-b4ef7-default-rtdb.firebaseio.com',
    storageBucket: 'singup-login-realtime-b4ef7.firebasestorage.app',
    iosBundleId: 'com.example.chatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGmBXV8Q6cSZYVPTW9XbeKpfg1GoW_4Os',
    appId: '1:1084688936474:web:f8b24bb778322c8f05aba3',
    messagingSenderId: '1084688936474',
    projectId: 'singup-login-realtime-b4ef7',
    authDomain: 'singup-login-realtime-b4ef7.firebaseapp.com',
    databaseURL: 'https://singup-login-realtime-b4ef7-default-rtdb.firebaseio.com',
    storageBucket: 'singup-login-realtime-b4ef7.firebasestorage.app',
  );
}
